export enum NotificationMessage {
  TaskDelete = 'Task deleted',
  AllTasksDelete = 'All tasks deleted',
  TaskAdd = 'Task added successfully',
  TaskMove = 'Task moved',
  Complete = 'Task completed',
  NotComplete = 'Task not completed',
  UpdateDate = 'Date updated successfully',
  UpdateTask = 'Task updated successfully',
  UpdateProject = 'Project updated successfully',
  DeleteProject = 'Project deleted',
  AddProject = 'Project added successfully',
  Duplicate = 'Task duplicated successfully',
  DuplicateProject = 'Project duplicated successfully',
  ArchiveProject = 'Project archived',
  ActivateProject = 'Project activated',
}
