export enum NotificationMessage {
  TaskDelete = 'Task deleted',
  AllTasksDelete = 'All tasks deleted',
  TaskAdd = 'Task added',
  TaskMove = 'Task moved',
  Complete = 'Task completed',
  NotComplete = 'Task activated',
  UpdateDate = 'Date updated',
  UpdateTask = 'Task updated',
  UpdateProject = 'Project updated',
  DeleteProject = 'Project deleted',
  AddProject = 'Project added',
  Duplicate = 'Task duplicated',
  DuplicateProject = 'Project duplicated',
  ArchiveProject = 'Project archived',
  ActivateProject = 'Project activated',
  TaskPriority = 'Task priority changed',
  CopyLink = 'Task link copied',
}
